# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件名称')),
                ('path', models.CharField(max_length=200, verbose_name='文件全路径')),
                ('relpath', models.CharField(max_length=200, verbose_name='文件所处路径')),
                ('views', models.IntegerField(default=0, verbose_name='点击数量')),
                ('anno_nums', models.IntegerField(default=0, verbose_name='注释数量')),
                ('summary', models.CharField(max_length=300, verbose_name='摘要')),
                ('note', models.CharField(max_length=300, verbose_name='首行注释')),
                ('has_summary', models.BooleanField(default=False, verbose_name='是否有注释')),
                ('file_index', models.IntegerField(default=0, verbose_name='文件索引')),
                ('code', models.TextField(default='', verbose_name='代码')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='工程名称')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='函数名称')),
                ('path', models.CharField(max_length=200, verbose_name='函数路径')),
                ('views', models.IntegerField(default=0, verbose_name='点击数量')),
                ('anno_nums', models.IntegerField(default=0, verbose_name='注释数量')),
                ('summary', models.CharField(max_length=300, verbose_name='摘要')),
                ('note', models.CharField(max_length=300, verbose_name='首行注释')),
                ('has_summary', models.BooleanField(default=False, verbose_name='是否有注释')),
                ('function_index', models.IntegerField(default=0, verbose_name='函数索引')),
                ('code', models.TextField(default='', verbose_name='代码')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.File', verbose_name='文件名称')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='工程名称')),
            ],
            options={
                'verbose_name': '函数',
                'verbose_name_plural': '函数',
            },
        ),
    ]
