# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_file_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_linenum', models.IntegerField(verbose_name='文件行号')),
                ('function_linenum', models.IntegerField(null=True, verbose_name='函数行号')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '代码行',
                'verbose_name_plural': '代码行',
            },
        ),
        migrations.AlterField(
            model_name='file',
            name='note',
            field=models.CharField(default='', max_length=300, verbose_name='首行注释'),
        ),
        migrations.AlterField(
            model_name='file',
            name='summary',
            field=models.CharField(default='', max_length=300, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='function',
            name='note',
            field=models.CharField(default='', max_length=300, verbose_name='首行注释'),
        ),
        migrations.AlterField(
            model_name='function',
            name='summary',
            field=models.CharField(default='', max_length=300, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='line',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.File', verbose_name='文件名称'),
        ),
        migrations.AddField(
            model_name='line',
            name='function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Function', verbose_name='函数'),
        ),
        migrations.AddField(
            model_name='line',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='工程名称'),
        ),
    ]
