# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_line_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.IntegerField(default=0, verbose_name='文件数量'),
        ),
        migrations.AddField(
            model_name='project',
            name='functions',
            field=models.IntegerField(default=0, verbose_name='方法数量'),
        ),
    ]
