# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20170927_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('callee_function_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callee', to='projects.Function', verbose_name='被调用函数')),
                ('caller_function_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caller', to='projects.Function', verbose_name='调用函数')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='工程名称')),
            ],
            options={
                'verbose_name': '调用关系',
                'verbose_name_plural': '调用关系',
            },
        ),
    ]
