# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 00:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_auto_20170929_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='数据ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='回答时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='点赞对象')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_anno', to='projects.File', verbose_name='文件')),
                ('function', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='function_anno', to='projects.Function', verbose_name='函数')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_anno', to='projects.Project', verbose_name='工程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '注释',
                'verbose_name_plural': '注释',
            },
        ),
    ]
