# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_comment', to='projects.File', verbose_name='文件'),
        ),
        migrations.AddField(
            model_name='comment',
            name='function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='function_comment', to='projects.Function', verbose_name='函数'),
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_comment', to='projects.Project', verbose_name='工程'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_comment', to='projects.Annotation', verbose_name='注释'),
        ),
    ]
