# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20170930_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='vote_down',
            field=models.IntegerField(default=0, verbose_name='点踩数量'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='vote_up',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
        migrations.AddField(
            model_name='comment',
            name='vote_down',
            field=models.IntegerField(default=0, verbose_name='点踩数量'),
        ),
        migrations.AddField(
            model_name='comment',
            name='vote_up',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
        migrations.AddField(
            model_name='file',
            name='vote_down',
            field=models.IntegerField(default=0, verbose_name='点踩数量'),
        ),
        migrations.AddField(
            model_name='file',
            name='vote_up',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
        migrations.AddField(
            model_name='function',
            name='vote_down',
            field=models.IntegerField(default=0, verbose_name='点踩数量'),
        ),
        migrations.AddField(
            model_name='function',
            name='vote_up',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
    ]
