# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20171010_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.IntegerField(default=0, verbose_name='点击数量'),
        ),
    ]
