# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='note',
            field=models.TextField(default='', verbose_name='首行注释'),
        ),
        migrations.AlterField(
            model_name='function',
            name='note',
            field=models.TextField(default='', verbose_name='首行注释'),
        ),
    ]
