# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20171011_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rel_path',
            field=models.CharField(max_length=200, null=True, verbose_name='工程相对路径'),
        ),
    ]
