# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20171011_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': ['-views'], 'verbose_name': '函数', 'verbose_name_plural': '函数'},
        ),
        migrations.AlterField(
            model_name='annotation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='回答时间'),
        ),
    ]
