# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20171018_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='回答时间'),
        ),
    ]
