# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20171018_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='has_question',
            field=models.BooleanField(default=False, verbose_name='是否添加0行问题'),
        ),
        migrations.AddField(
            model_name='file',
            name='has_sonar',
            field=models.BooleanField(default=False, verbose_name='是否通过sonar获取问题'),
        ),
        migrations.AddField(
            model_name='function',
            name='has_question',
            field=models.BooleanField(default=False, verbose_name='是否添加0行问题'),
        ),
        migrations.AddField(
            model_name='function',
            name='has_sonar',
            field=models.BooleanField(default=False, verbose_name='是否通过sonar获取问题'),
        ),
    ]
