# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20171101_1629'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['object_id', 'user_id'], name='projects_an_object__63bde9_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['views'], name='projects_fi_views_38a5b5_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['created'], name='projects_fi_created_1f8f63_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['views'], name='projects_pr_views_1e1884_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created'], name='projects_pr_created_3ef374_idx'),
        ),
    ]
