# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20171101_1646'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['created'], name='projects_fi_created_1f8f63_idx'),
        ),
    ]
