# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20171101_1651'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['object_id', 'user_id'], name='projects_an_object__63bde9_idx'),
        ),
    ]
