# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20171101_1656'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='file',
            name='projects_fi_views_38a5b5_idx1',
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['views'], name='projects_fi_views_38a5b5_idx'),
        ),
    ]
