# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('vote_up', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('vote_down', models.IntegerField(default=0, verbose_name='点踩数量')),
                ('created', models.DateField(auto_now_add=True, verbose_name='回答时间')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='数据ID')),
                ('question_type', models.CharField(choices=[('1', '系统'), ('2', '用户')], default='1', max_length=3, verbose_name='问题类型')),
                ('question_level', models.CharField(choices=[('jd', '简单'), ('zd', '中等'), ('n', '难')], default='jd', max_length=5, verbose_name='问题类型')),
                ('vote_up', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('vote_down', models.IntegerField(default=0, verbose_name='点踩数量')),
                ('created', models.DateField(auto_now_add=True, verbose_name='提问时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='提问对象')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Question', verbose_name='问题'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
