# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField(default='', verbose_name='选项内容')),
                ('choice_position', models.CharField(default='', max_length=10, verbose_name='选项位置')),
                ('created', models.DateField(auto_now_add=True, verbose_name='提问时间')),
            ],
            options={
                'verbose_name': '选择题选项',
                'verbose_name_plural': '选择题选项',
            },
        ),
        migrations.CreateModel(
            name='QuestionStandardAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_position', models.CharField(default='', max_length=10, verbose_name='正确选项位置')),
                ('created', models.DateField(auto_now_add=True, verbose_name='提问时间')),
            ],
            options={
                'verbose_name': '标准答案',
                'verbose_name_plural': '标准答案',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_source',
            field=models.CharField(choices=[('1', '系统'), ('2', '用户')], default='1', max_length=3, verbose_name='问题类型'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('1', '选择题'), ('2', '判断题'), ('3', '问答题')], default='1', max_length=3, verbose_name='问题类型'),
        ),
        migrations.AddField(
            model_name='questionstandardanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Question', verbose_name='问题'),
        ),
        migrations.AddField(
            model_name='questionchoices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Question', verbose_name='问题'),
        ),
    ]
