# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20171010_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='function_content',
            field=models.TextField(null=True, verbose_name='函数问题内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(default='', verbose_name='文件问题内容'),
        ),
        migrations.AlterField(
            model_name='questionchoices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_choices', to='qa.Question', verbose_name='问题'),
        ),
    ]
