# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_answer_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file_id',
            field=models.IntegerField(default=0, verbose_name='方法'),
        ),
        migrations.AddField(
            model_name='question',
            name='function_id',
            field=models.IntegerField(default=0, verbose_name='函数'),
        ),
    ]
