# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_auto_20171011_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file_linenum',
            field=models.IntegerField(default=0, verbose_name='文件行号'),
        ),
        migrations.AddField(
            model_name='question',
            name='function_linenum',
            field=models.IntegerField(default=0, verbose_name='问题行号'),
        ),
        migrations.AddField(
            model_name='question',
            name='sonar_id',
            field=models.IntegerField(default=0, verbose_name='Sonar'),
        ),
    ]
