# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-12 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_auto_20171011_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file_linenum',
            field=models.IntegerField(null=True, verbose_name='文件行号'),
        ),
        migrations.AlterField(
            model_name='question',
            name='function_linenum',
            field=models.IntegerField(null=True, verbose_name='问题行号'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sonar_id',
            field=models.IntegerField(null=True, verbose_name='Sonar'),
        ),
    ]
