# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0010_auto_20171013_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_info',
            field=models.CharField(choices=[('1', '错误程度'), ('2', '错误类型'), ('3', '错误行号')], max_length=3, null=True, verbose_name='问题信息'),
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Question', verbose_name='问题'),
        ),
    ]
