# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0011_auto_20171018_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='回答时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提问时间'),
        ),
        migrations.AlterField(
            model_name='questionchoices',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提问时间'),
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='questionstandardanswers',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提问时间'),
        ),
    ]
