# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0012_auto_20171018_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstandardanswers',
            name='choice_position',
            field=models.CharField(default='', max_length=500, verbose_name='正确选项位置'),
        ),
    ]
