# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0013_auto_20171030_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file_id',
            field=models.IntegerField(db_index=True, null=True, verbose_name='文件'),
        ),
    ]
