# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0014_auto_20171101_1629'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='SonarResult',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('project_id', models.IntegerField(null=True)),
        #         ('blob_id', models.IntegerField(null=True)),
        #         ('blob_line', models.IntegerField(null=True)),
        #         ('function_id', models.IntegerField(null=True)),
        #         ('function_line', models.IntegerField(null=True)),
        #         ('rule_id', models.IntegerField(null=True)),
        #         ('rule_name', models.CharField(max_length=255, null=True)),
        #         ('rule_priority', models.IntegerField(null=True)),
        #         ('message', models.CharField(max_length=4000, null=True)),
        #         ('effort', models.IntegerField(null=True)),
        #         ('status', models.CharField(max_length=20, null=True)),
        #         ('severity', models.CharField(max_length=10, null=True)),
        #         ('has_question', models.IntegerField(null=True)),
        #     ],
        #     options={
        #         'db_table': 'sonar_results',
        #     },
        # ),
        # migrations.AlterField(
        #     model_name='question',
        #     name='file_id',
        #     field=models.IntegerField(null=True, verbose_name='文件'),
        # ),
        # migrations.AddIndex(
        #     model_name='answer',
        #     index=models.Index(fields=['question_id', 'user_id'], name='qa_answer_questio_a711c8_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='question',
        #     index=models.Index(fields=['file_id', 'file_linenum', 'question_info'], name='qa_question_file_id_482a12_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='question',
        #     index=models.Index(fields=['function_id', 'file_linenum', 'question_info'], name='qa_question_functio_bca5e3_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='question',
        #     index=models.Index(fields=['function_id', 'function_linenum', 'question_info'], name='qa_question_functio_5c510d_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='question',
        #     index=models.Index(fields=['file_id', 'file_linenum'], name='qa_question_file_id_205ed1_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='question',
        #     index=models.Index(fields=['function_id', 'file_linenum'], name='qa_question_functio_0d5f0f_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='question',
        #     index=models.Index(fields=['file_id'], name='qa_question_file_id_901087_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='question',
        #     index=models.Index(fields=['function_id'], name='qa_question_functio_a54c36_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='sonarresult',
        #     index=models.Index(fields=['blob_id'], name='sonar_resul_blob_id_46c5c6_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='sonarresult',
        #     index=models.Index(fields=['project_id'], name='sonar_resul_project_a870cc_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='sonarresult',
        #     index=models.Index(fields=['function_id'], name='sonar_resul_functio_ca2854_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='sonarresult',
        #     index=models.Index(fields=['severity'], name='sonar_resul_severit_1cdab2_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='sonarresult',
        #     index=models.Index(fields=['has_question'], name='sonar_resul_has_que_369c69_idx'),
        # ),
    ]
