# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0015_auto_20171101_1636'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['function_id', 'file_linenum'], name='qa_question_functio_0d5f0f_idx'),
        ),
    ]
