# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0017_auto_20171101_1651'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question_id', 'user_id'], name='qa_answer_questio_a711c8_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['function_id', 'function_linenum', 'question_info'], name='qa_question_functio_5c510d_idx'),
        ),
    ]
