# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171018_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('1', '学生'), ('2', '老师')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
