# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0003_auto_20170310_1335'),
        ('xadmin', '0003_auto_20160715_0100'),
    ]

    operations = [
    ]
