# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20170928_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservote',
            name='vote_value',
            field=models.IntegerField(choices=[(1, '点赞'), (-1, '点踩')], default=0, verbose_name='类型'),
        ),
    ]
