# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20170928_1101'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='uservote',
            index=models.Index(fields=['user_id', 'vote_type_id', 'vote_id'], name='operations__user_id_e88559_idx'),
        ),
    ]
